# Generated by Django 6.0.2 on 2026-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_options_alter_itemimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(choices=[('cairo', 'Cairo'), ('alexandria', 'Alexandria'), ('giza', 'Giza'), ('sharm', 'Sharm El-Sheikh'), ('hurghada', 'Hurghada'), ('luxor', 'Luxor'), ('aswan', 'Aswan'), ('mansoura', 'Mansoura'), ('tanta', 'Tanta'), ('port_said', 'Port Said'), ('suez', 'Suez'), ('ismailia', 'Ismailia'), ('zagazig', 'Zagazig'), ('damanhur', 'Damanhur'), ('minya', 'Minya'), ('assiut', 'Assiut'), ('sohag', 'Sohag'), ('qena', 'Qena'), ('banha', 'Banha'), ('kafr_sheikh', 'Kafr El-Sheikh')], default='mansoura', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
