# Generated by Django 6.0.2 on 2026-02-25 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_city_alter_category_slug_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=uuid.uuid4, unique=True),
        ),
    ]
